name: Push
description: Push a container image

inputs:
  registry:
    description: Registry
    required: true
  repository:
    description: Repository
    required: true
  tags:
    description: Comma-seperated list of image tags
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      env:
        BUILDAH_ISOLATION: chroot
        BUILDAH_LAYERS: "true"
        STORAGE_DRIVER: vfs
        IMAGE_NAME: ${{ inputs.registry }}/${{ inputs.repository }}
        TAGS: ${{ inputs.tags }}
      run: |
        echo "Building ${IMAGE_NAME} from ${CONTAINER_FILE}"
        buildah build \
          --cache-from ${IMAGE_NAME}-cache \
          --cache-to ${IMAGE_NAME}-cache \
          -t ${IMAGE_NAME} \
          -f ${CONTAINER_FILE} \
          .

        for TAG in ${TAGS//,/ };
        do
          echo "Pushing ${IMAGE_NAME} ${IMAGE_NAME}:${TAG}"
          buildah push ${IMAGE_NAME} ${IMAGE_NAME}:${TAG};
        done
