on:
  workflow_call:
    inputs:
      registry:
        description: Registry
        required: true
      repository:
        description: Repository
        required: true
      tag:
        description: Image
        required: true
      container_file:
        description: Container file
        required: true

jobs:
  build:
    runs-on: docker
    container:
      image: quay.io/buildah/stable
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - run: |
          buildah build \
            --storage-driver vfs \
            --isolation chroot \
            --layers \
            --cache-from ${{ inputs.registry }}/${{ inputs.repository }}-cache \
            --cache-to ${{ inputs.registry }}/${{ inputs.repository }}-cache \
            -t ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.tag }} \
            -t ${{ inputs.registry }}/${{ inputs.repository }}:latest \
            -f ${{ inputs.container_file }} \
            .
          buildah push --storage-driver vfs ${{ inputs.registry }}/${{ inputs.repository }}:${{ inputs.tag }}
          buildah push --storage-driver vfs ${{ inputs.registry }}/${{ inputs.repository }}:latest
