on:
  push:
    branches:
      - master

env:
  REGISTRY: registry.home.wtrhs.com
  REPOSITORY: wtrhs/blog
  IMAGE_TAG: latest

jobs:
  build:
    runs-on: docker
    container:
      image: registry.home.wtrhs.com/library/node:20-bookworm
      options: --device /dev/fuse --security-opt label=disable --security-opt seccomp=unconfined
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - env:
          BUILDAH_ISOLATION: chroot
        run: |
          apt update -y && apt install -y buildah

          buildah build \
            --layers \
            --cache-from $REGISTRY/$REPOSITORY-cache \
            --cache-to $REGISTRY/$REPOSITORY-cache \
            -t $REGISTRY/$REPOSITORY:$IMAGE_TAG \
            -f deploy/Containerfile \
            .
          buildah push $REGISTRY/$REPOSITORY:$IMAGE_TAG
