on:
  push:
    branches:
      - master

env:
  REGISTRY: registry.home.wtrhs.com
  REPOSITORY: wtrhs/blog
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    runs-on: docker
    container:
      image: registry.home.wtrhs.com/wtrhs/ci-deploy:latest
      options: --volume /var/run/secrets/kubernetes.io/serviceaccount:/var/run/secrets/kubernetes.io/serviceaccount:ro
    steps:
      # - uses: https://code.forgejo.org/actions/checkout@v4
      - run: |
          echo "${{ secrets.KUBERNETES_CA_CRT }}" | base64 --decode > ca.crt
          kubectl config set-cluster home --server=https://home-server.lan:16443 --certificate-authority=ca.crt
          kubectl config set-credentials ci --token=$( echo "${{ secrets.KUBERNETES_SERVICE_ACCOUNT_TOKEN }}" | base64 --decode )
          kubectl config set-context ci --user=ci --namespace=personal --cluster=home
          kubectl config use-context ci
          kubectl config view
          kubectl get deployments.apps
