name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-test-push:
    runs-on: docker
    container:
      image: registry.home.wtrhs.com/wtrhs/ci
      volumes:
        # Access to the kubectl proxy socket for deployment
        - /kubectl-proxy-socket:/kubectl-proxy-socket
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - uses: ./.forgejo/actions/build
        with:
          registry: registry.home.wtrhs.com
          repository: wtrhs/blog
          container_file: deploy/Containerfile
      - uses: ./.forgejo/actions/test
        with:
          image: registry.home.wtrhs.com/wtrhs/blog
      - uses: ./.forgejo/actions/push
        with:
          registry: registry.home.wtrhs.com
          repository: wtrhs/blog
          tags: ${{ github.sha }},latest

  deploy:
    needs: [build-test-push]
    runs-on: docker
    container:
      image: registry.home.wtrhs.com/wtrhs/ci
    env:
      IMAGE_NAME: registry.home.wtrhs.com/wtrhs/blog
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - run: |
          # Check image exists first
          skopeo inspect --no-tags docker://${IMAGE_NAME}:${IMAGE_TAG}

          # Setup SSH
          mkdir -p ~/.ssh
          echo "${{ secrets.CI_SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 0400 ~/.ssh/id_ed25519
          ssh-keyscan -t ed25519 codeberg.org >> ~/.ssh/known_hosts

          # Clone the git repository
          git config --global user.email "ci@codeberg.org"
          git config --global user.name "ci"
          git clone git@codeberg.org:jwtrhs/home-server.git .

          # Modify the image tag
          cd k8s/personal
          kustomize edit set image ${IMAGE_NAME}:${IMAGE_TAG}

          # Commit the modified files back to the repository
          git add .
          git commit -m "CD - Setting image ${IMAGE_NAME} tag to ${IMAGE_TAG}"
          git push
