name: Merge

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-test-push-deploy:
    runs-on: home-server
    container:
      image: registry.home.wtrhs.com/wtrhs/ci-cd
      volumes:
        - /var/run/secrets/kubernetes.io/serviceaccount:/var/run/secrets/kubernetes.io/serviceaccount
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - uses: ./.forgejo/actions/build
        with:
          registry: registry.home.wtrhs.com
          repository: wtrhs/blog:latest
          container_file: Containerfile
      - uses: ./.forgejo/actions/test
        with:
          image: registry.home.wtrhs.com/wtrhs/blog:latest
      - name: Set current date as env variable
        run: echo "NOW=$(date +%s)" >> $GITHUB_ENV
      - uses: ./.forgejo/actions/push
        with:
          registry: registry.home.wtrhs.com
          repository: wtrhs/blog:latest
          tags: ${{ github.ref_name }}-${{ github.sha }}-${{ env.NOW }},latest
      - name: Update image tag
        env:
          IMAGE_NAME: registry.home.wtrhs.com/wtrhs/blog
          IMAGE_TAG: ${{ github.ref_name }}-${{ github.sha }}-${{ env.NOW }}
        run: |
          curl -X POST https://codeberg.org/api/v1/repos/jwtrhs/infra/actions/workflows/deploy-image.yaml/dispatches -H "Accept: application/json" -H "Authorization: Bearer ${{ secrets.FORGEJO_CI_TOKEN }}" --json "{\"ref\": \"main\", \"inputs\": {\"cluster\": \"production\", \"path\": \"k8s/apps/production\", \"image-name\": \"${IMAGE_NAME}\", \"image-tag\": \"${IMAGE_TAG}\"}}" -v
