on:
  pull_request:

jobs:
  test:
    runs-on: docker
    container:
      image: alpine
    steps:
      - run: apk add curl git nodejs uv
      - uses: https://code.forgejo.org/actions/checkout@v4
      - run: uv install python
      - run: uv tool run ruff check
      - run: uv run pytest
