on: [push]
jobs:
  test:
    runs-on: docker
    container:
      image: registry.home.wtrhs.com/library/python:alpine
    steps:
      - run: |
          python3 -m venv .venv
          . .venv/bin/activate
          python3 -m pip install -q -r requirements-test.txt -r requirements.txt
          black --check --diff .
          flake8
          pytest
