on:
  pull_request:

jobs:
  test:
    runs-on: docker
    container:
      image: alpine
    steps:
      - run: apk add curl git nodejs
      - uses: https://code.forgejo.org/actions/checkout@v4
      - run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - run: uv tool run ruff check
      - run: uv run pytest
