on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build-and-test:
    runs-on: docker
    container:
      image: alpine
    steps:
      - run: apk add buildah git nodejs
      - uses: https://code.forgejo.org/actions/checkout@v4
      - uses: ./.forgejo/actions/build
        with:
          registry: registry.home.wtrhs.com
          repository: wtrhs/blog
          tags: ${{ github.sha }},latest
          container_file: deploy/Containerfile
  # test:
  #   runs-on: docker
  #   container:
  #     image: python:alpine
  #   steps:
  #     - run: apk add git nodejs uv
  #     - uses: https://code.forgejo.org/actions/checkout@v4
  #     - run: uv tool run ruff check
  #     - run: uv run pytest
