on:
  workflow_call:

jobs:
  test:
    runs-on: docker
    container:
      image: registry.home.wtrhs.com/library/node:20-bookworm
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv tool run ruff check
          uv run pytest
