on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: docker
    container:
      image: registry.home.wtrhs.com/wtrhs/ci
    steps:
      - uses: https://code.forgejo.org/actions/checkout@v4
      - uses: ./.forgejo/actions/build
        with:
          registry: registry.home.wtrhs.com
          repository: wtrhs/blog
          tags: ${{ github.sha }}
          container_file: deploy/Containerfile

  test:
    needs: [build]
    runs-on: docker
    container:
      image: registry.home.wtrhs.com/wtrhs/ci
    steps:
      - run: podman run registry.home.wtrhs.com/wtrhs/blog:${{ github.sha }} uv tool run ruff check
      - run: podman run registry.home.wtrhs.com/wtrhs/blog:${{ github.sha }} uv run pytest
