namespace: blog

resources:
- ../base
- certificate.yaml
- gateway.yaml

patches:
- path: patch-deployment-certificates.yaml
  target:
    kind: Deployment
    name: blog

images:
- name: registry.home.wtrhs.com/wtrhs/blog
  newTag: 1102548973daaacd33d64d46d1914b040d32ac3a

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
