namespace: blog

resources:
- ../base
- certificate.yaml
- gateway.yaml

patches:
- path: patch-deployment-certificates.yaml
  target:
    kind: Deployment
    name: blog

images:
- name: registry.home.wtrhs.com/wtrhs/blog
  newTag: 205233a4ad82e8d837bee9818525c70d75047d4e

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
