namespace: blog

resources:
- ../base
- certificate.yaml
- gateway.yaml

images:
- name: registry.home.wtrhs.com/wtrhs/blog
  newTag: 11da2d0389346d1678b89e4ff3da022de17866f8

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
