namespace: blog

resources:
- namespace.yaml
- blog.yaml

images:
- name: registry.home.wtrhs.com/wtrhs/blog
  newTag: 91d986036bfe56b44234f2b3204d4e6723582cd6

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
