namespace: blog

resources:
- namespace.yaml
- blog.yaml

images:
- name: registry.home.wtrhs.com/wtrhs/blog
  newTag: 6fd0a585421b448019396e493b022ed584f9127a

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
