FROM python:3.13-alpine

RUN apk add uv

RUN mkdir /srv/app
WORKDIR /srv/app

COPY . .

# Cannot install python in musl distributions yet
# see: https://github.com/astral-sh/uv/issues/6890
# RUN uv python install
RUN uv sync

CMD ["uv", "run", "python", "-m", "blog.app"]
