FROM python:alpine

RUN mkdir /srv/app
WORKDIR /srv/app

ENV VIRTUAL_ENV=/opt/venv
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

COPY requirements.txt .
RUN python -m pip install -r requirements.txt

COPY deploy/entrypoint.sh .
COPY content/ content/
COPY blog/ blog/
COPY static static/
COPY template/ template/

RUN ls -lah .

CMD ["python", "-m", "blog.app"]
