import os

STATIC_DIRECTORY = os.getenv("BLOG_STATIC_DIRECTORY", "static")
TEMPLATE_DIRECTORY = os.getenv("BLOG_TEMPLATE_DIRECTORY", "template")
ARTICLE_DIRECTORY = os.getenv("BLOG_ARTICLE_DIRECTORY", "article")
