apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog
  labels:
    app: blog
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
        - name: blog
          image: registry.home.wtrhs.com/wtrhs/blog
          imagePullPolicy: Always
          ports:
            - containerPort: 8888
          livenessProbe:
            initialDelaySeconds: 5
            periodSeconds: 5
            httpGet:
              scheme: HTTP
              port: 8888
          resources:
            limits:
              cpu: 500m
              memory: 256M
---
apiVersion: v1
kind: Service
metadata:
  name: blog
spec:
  selector:
    app: blog
  ports:
    - name: blog
      port: 8888
      targetPort: 8888
