on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: self-hosted
    # container:
    #   image: registry.home.wtrhs.com/library/node:20-bookworm
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/test
  build:
    needs: [test]
    runs-on: self-hosted
    # container:
    #   image: registry.home.wtrhs.com/library/node:20-bookworm
    #   options: --device /dev/fuse --security-opt label=disable --security-opt seccomp=unconfined
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          cache-from: type=registry,ref=registry.home.wtrhs.com/wtrhs/blog:${{ github.sha }}-cache
          cache-to: type=registry,ref=registry.home.wtrhs.com/wtrhs/blog:${{ github.sha }}-cache,mode=max
          file: deploy/Containerfile
          push: true
          tags: registry.home.wtrhs.com/wtrhs/blog:${{ github.sha }},registry.home.wtrhs.com/wtrhs/blog:latest
  deploy:
    needs: [build]
    runs-on: self-hosted
    # container:
    #   image: registry.home.wtrhs.com/wtrhs/ci-deploy:latest
    #   options: --volume /var/run/secrets/kubernetes.io/serviceaccount:/var/run/secrets/kubernetes.io/serviceaccount:ro
    steps:
      - run: |
          echo "${{ secrets.KUBERNETES_CA_CRT }}" | base64 --decode > ca.crt
          kubectl config set-cluster home --server=https://home-server.lan:16443 --certificate-authority=ca.crt
          kubectl config set-credentials ci --token=$( echo "${{ secrets.KUBERNETES_SERVICE_ACCOUNT_TOKEN }}" | base64 --decode )
          kubectl config set-context ci --user=ci --namespace=personal --cluster=home
          kubectl config use-context ci
          kubectl config view
          kubectl -n personal rollout restart deployment blog
